resources:
  - name: repo-master
    type: git
    source:
      uri: git@github.com:myminseok/concourse-demo.git
      branch: master
      private_key: {{github-private-key}}
    check_every: 10s
  - name: m2
    type: docker-image
    source:
      repository: making/m2
  - name: cf-dev
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space-dev}}
      skip_cert_check: true

jobs:
  - name: test-master-job
    serial: true
    public: true
    plan:
      - aggregate: 
        - get: repo
          resource: repo-master
          trigger: true
        - get: m2
      - task: unit
        file: repo/ci/tasks/unit.yml
  - name: deploy-develop-job
    serial: true
    public: false
    plan:
      - aggregate:
        - get: m2
        - get:  repo
          resource: repo-master
          passed: [ test-master ]
          trigger: true
      - task: build
        file: repo/ci/tasks/build.yml
      - put: cf-dev
        params:
          manifest: repo/manifest-dev.yml
          path: output/demo.jar
          current_app_name: concourse-demo-dev
