resources:
  - name: repo-develop
    type: git
    source:
      uri: git@github.com:myminseok/concourse-demo.git
      branch: develop
      private_key: {{github-private-key}}
    check_every: 10s
  - name: repo-master
    type: git
    source:
      uri: git@github.com:myminseok/concourse-demo.git
      branch: master
      private_key: {{github-private-key}}
    check_every: 10s
  - name: m2
    type: docker-image
    source:
      repository: ubuntu
jobs:
  - name: test-master
    serial: true
    public: true
    plan:
      - aggregate: 
        - get: repo
          resource: repo-develop
          trigger: true
        - get: m2
      - task: unit
        file: repo/ci/tasks/unit.yml
      - put: repo
        resource: repo-master
        params:
           repository: out